# Generated by Django 5.2.5 on 2025-09-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_contact_alter_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
