# Generated by Django 5.2.5 on 2025-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
