# Generated by Django 5.2.5 on 2025-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default-slug", max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
