# Generated by Django 5.2.5 on 2025-10-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
