# Generated by Django 5.2.7 on 2025-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0009_news_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
