# Generated by Django 5.2.7 on 2025-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0010_news_content_en_news_content_ru_news_content_uz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="content_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="content_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_ru",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uz",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
