# Generated by Django 5.2.7 on 2025-10-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0011_alter_news_content_en_alter_news_content_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="content_uz",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_uz",
        ),
    ]
