# Generated by Django 5.2.7 on 2025-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0012_remove_news_content_uz_remove_news_title_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
